### ISSUE TITLE
Cool free ringtones

### ISSUE THREAD

**Issue by twij** [kirjavascript/nibblrjr#2]
Hi,

Can I have an option I can set with say ~leavemealone where the bot puts a space in the middle of my nick when it spews out random commands. This is so it'll stop making my Windows™ Task Bar™ flash all the time when it highlights me because it's every 4 seconds and it makes it look more Fisher Price (also ™ I think). 

If not I can install Linux.

Thank you
~braf
xox

**Comment by kirjavascript** [comment]
better support for windows is being added every day pls bear with us

**Comment by twij** [comment]
Can we also get a feature where we can set it to ignore banks? Like not respond to any of his commands for no reason.

**Comment by kirjavascript** [comment]
> Can we also get a feature where we can set it to ignore banks? Like not respond to any of his commands for no reason.

both of these are done now basically lmao
